name: build installers
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - installers/**

# Two separate jobs, first for multiarch (amd64, arm64), second for amd64 only

jobs:
  # pushMultiArch:
  #   name: "yolks:installers_multiarch:${{ matrix.tag }}"
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       tag:
  #         - alpine
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: docker/setup-buildx-action@v2
  #       with:
  #         buildkitd-flags: --debug
  #     - name: Setup QEMU for multiarch builds
  #       uses: docker/setup-qemu-action@v2
  #       with:
  #         platforms: arm64,amd64
  #     - uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.REGISTRY_TOKEN }}
  #     - uses: docker/build-push-action@v4
  #       with:
  #         context: ./installers
  #         file: ./installers/${{ matrix.tag }}/Dockerfile
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: |
  #           ghcr.io/pterodactyl/installers:${{ matrix.tag }}

  pushAmd:
    name: "yolks:installers_amd:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        tag:
          - debian
    steps:
      - uses: actions/checkout@v3
      - 
        name: set lower case owner name
        run: |
          echo "REPOSITORY_OWNER_LOWERCASE=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./installers
          file: ./installers/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.REPOSITORY_OWNER_LOWERCASE }}/installers:${{ matrix.tag }}
